In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
spotify = pd.read_csv('decades.csv')
spotify.head()

,Unnamed: 0,url,WeekID,Week Position,Song_x,Performer_x,SongID,Instance,Previous Week Position,Peak Position,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,year,Decade
0,1,http://www.billboard.com/charts/hot-100/2014-0...,3/22/2014,45,Sail,AWOLNATION,SailAWOLNATION,2,41.0,17,...,1.0,0.0568,0.452,0.609,0.0953,0.243,119.038,4.0,2014,2010s
1,2,http://www.billboard.com/charts/hot-100/2009-1...,10/10/2009,48,I'm Yours,Jason Mraz,I'm YoursJason Mraz,1,49.0,6,...,1.0,0.0468,0.595,0.000,0.1050,0.718,150.953,4.0,2009,2000s
2,3,http://www.billboard.com/charts/hot-100/1998-1...,10/10/1998,45,How Do I Live,LeAnn Rimes,How Do I LiveLeAnn Rimes,1,48.0,2,...,1.0,0.0279,0.128,0.000,0.0822,0.258,128.303,4.0,1998,1990s
3,6,http://www.billboard.com/charts/hot-100/2012-0...,4/14/2012,49,Rolling In The Deep,Adele,Rolling In The DeepAdele,2,43.0,1,...,1.0,0.0294,0.131,0.000,0.0527,0.522,104.945,4.0,2012,2010s
4,8,http://www.billboard.com/charts/hot-100/2007-1...,12/1/2007,47,Before He Cheats,Carrie Underwood,Before He CheatsCarrie Underwood,1,43.0,8,...,0.0,0.0405,0.271,0.000,0.1190,0.290,147.905,4.0,2007,2000s

In [3]:
spotify['Peak Position'].mask(spotify['Peak Position'] == 1, 'Number1', inplace=True)

In [4]:
spotify['Peak Position'].mask(spotify['Peak Position'] != 'Number1', 'NotNumber1', inplace=True)

In [5]:
dropped = spotify.drop(["Weeks on Chart","year", "WeekID", "Unnamed: 0", "url", "spotify_track_id", "spotify_track_explicit", "Week Position", "Song_x", "Performer_x", "Instance", "Previous Week Position", "Performer_y", "Song_y", "spotify_genre", "spotify_track_preview_url","spotify_track_album", "spotify_track_duration_ms", "Decade", "SongID" ], axis=1)

In [6]:
dropped2 =dropped.drop(["key", "mode", "liveness", "tempo", "time_signature"], axis=1)

In [7]:
dropped2

,Peak Position,spotify_track_popularity,danceability,energy,loudness,speechiness,acousticness,instrumentalness,valence
0,NotNumber1,74.0,0.825,0.435,-9.582,0.0568,0.452,0.609000,0.243
1,NotNumber1,83.0,0.686,0.457,-8.322,0.0468,0.595,0.000000,0.718
2,NotNumber1,68.0,0.577,0.462,-7.989,0.0279,0.128,0.000000,0.258
3,Number1,76.0,0.729,0.756,-5.119,0.0294,0.131,0.000000,0.522
4,NotNumber1,74.0,0.519,0.749,-3.318,0.0405,0.271,0.000000,0.290
...,...,...,...,...,...,...,...,...,...
10713,NotNumber1,64.0,0.884,0.814,-5.333,0.3030,0.154,0.000002,0.907
10714,NotNumber1,74.0,0.588,0.567,-3.738,0.0628,0.221,0.000000,0.113
10715,NotNumber1,71.0,0.643,0.503,-8.370,0.2160,0.273,0.000000,0.598
10716,NotNumber1,54.0,0.701,0.915,-3.887,0.1280,0.171,0.000000,0.698
10717,NotNumber1,80.0,0.702,0.708,-5.366,0.0547,0.201,0.000000,0.713

In [8]:
sort = dropped2.sort_values(by=['Peak Position'], ascending=False)

In [9]:
sort

,Peak Position,spotify_track_popularity,danceability,energy,loudness,speechiness,acousticness,instrumentalness,valence
824,Number1,74.0,0.808,0.535,-12.521,0.0353,0.17900,0.000099,0.848
5166,Number1,60.0,0.661,0.557,-8.244,0.0490,0.26200,0.000000,0.957
3363,Number1,67.0,0.714,0.935,-5.195,0.0849,0.05290,0.093400,0.725
5158,Number1,55.0,0.593,0.354,-10.269,0.0288,0.73300,0.000000,0.793
555,Number1,39.0,0.626,0.907,-7.488,0.0704,0.08510,0.000003,0.970
...,...,...,...,...,...,...,...,...,...
3830,NotNumber1,58.0,0.287,0.958,-4.331,0.0701,0.00547,0.016700,0.579
3831,NotNumber1,33.0,0.619,0.527,-9.376,0.0628,0.06920,0.000000,0.242
3832,NotNumber1,61.0,0.704,0.701,-8.031,0.4600,0.54900,0.000000,0.618
3833,NotNumber1,21.0,0.727,0.697,-10.194,0.0579,0.01690,0.005810,0.909
10717,NotNumber1,80.0,0.702,0.708,-5.366,0.0547,0.20100,0.000000,0.713

In [10]:
top700 = sort.head(7000)

In [11]:
top700

,Peak Position,spotify_track_popularity,danceability,energy,loudness,speechiness,acousticness,instrumentalness,valence
824,Number1,74.0,0.808,0.535,-12.521,0.0353,0.17900,0.000099,0.848
5166,Number1,60.0,0.661,0.557,-8.244,0.0490,0.26200,0.000000,0.957
3363,Number1,67.0,0.714,0.935,-5.195,0.0849,0.05290,0.093400,0.725
5158,Number1,55.0,0.593,0.354,-10.269,0.0288,0.73300,0.000000,0.793
555,Number1,39.0,0.626,0.907,-7.488,0.0704,0.08510,0.000003,0.970
...,...,...,...,...,...,...,...,...,...
431,NotNumber1,72.0,0.502,0.417,-7.665,0.0718,0.12700,0.004190,0.218
432,NotNumber1,79.0,0.307,0.433,-10.057,0.0290,0.38800,0.000091,0.224
455,NotNumber1,43.0,0.779,0.797,-7.081,0.0581,0.00975,0.024900,0.960
459,NotNumber1,64.0,0.670,0.476,-6.253,0.0406,0.32800,0.000000,0.235
506,NotNumber1,56.0,0.656,0.756,-6.516,0.0399,0.00785,0.000035,0.542

In [12]:
top700['Peak Position'].value_counts()

NotNumber1    6516
Number1        484
Name: Peak Position, dtype: int64

In [13]:
# Assign X (data) and y (target)
X = top700.drop("Peak Position", axis=1)
y = top700["Peak Position"]
print(X.shape, y.shape)

(7000, 8) (7000,)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [15]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
classifier.fit(X_train, y_train)

/Users/davidlopez/anaconda3/envs/PythonWebMongo/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9295238095238095
Testing Data Score: 0.9285714285714286

In [28]:
predictions = classifier.predict(X_test)
print(f"First 1000 Predictions:   {predictions[:10]}")
print(f"First 1000 Actual labels: {y_test[:10].tolist()}")

First 1000 Predictions:   ['NotNumber1' 'NotNumber1' 'NotNumber1' 'NotNumber1' 'NotNumber1'
 'NotNumber1' 'NotNumber1' 'NotNumber1' 'NotNumber1' 'Number1']
First 1000 Actual labels: ['NotNumber1', 'NotNumber1', 'NotNumber1', 'NotNumber1', 'NotNumber1', 'Number1', 'NotNumber1', 'NotNumber1', 'NotNumber1', 'Number1']

In [19]:
DataFrame = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

In [25]:
DataFrame.sort_values(by = 'Actual', ascending=False).head(10)

      Prediction   Actual
1190  NotNumber1  Number1
317   NotNumber1  Number1
151   NotNumber1  Number1
977   NotNumber1  Number1
733   NotNumber1  Number1
1665  NotNumber1  Number1
94       Number1  Number1
1362  NotNumber1  Number1
823   NotNumber1  Number1
541   NotNumber1  Number1

In [26]:
#When the coefficients are in scientific notation 1.2e+01 would be 12, 1.2e+00 would be 1.2, 1.2e-01 would be 0.12
classifier.coef_

array([[ 0.07387613, -0.61928335, -1.81894969, -0.04961366, -2.12846692,
         0.5311817 , -0.11148868,  1.52026174]])

In [22]:
DataFrame["Prediction"].value_counts()

NotNumber1    1740
Number1         10
Name: Prediction, dtype: int64

In [23]:
DataFrame["Actual"].value_counts()

NotNumber1    1629
Number1        121
Name: Actual, dtype: int64